In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\dell\Desktop\machine learning\Naive Bayes\project1\DiseaseAndSymptoms.csv")
df

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df.fillna("")

In [6]:
df

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,
3,Fungal infection,itching,skin_rash,dischromic _patches,,,,,,,,,,,,,,
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,,,,,,,,,,,
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,,,,,,,,,,,,,
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,,,,,,,,,,,,,
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,,,,,,,,,,,
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,,,,,,,,,,,,

In [7]:
X = df.iloc[:,1:]
X

,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,
1,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,
2,itching,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,
3,itching,skin_rash,dischromic _patches,,,,,,,,,,,,,,
4,itching,skin_rash,nodal_skin_eruptions,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,,,,,,,,,,,
4916,skin_rash,pus_filled_pimples,blackheads,scurring,,,,,,,,,,,,,
4917,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,,,,,,,,,,,,,
4918,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,,,,,,,,,,,
4919,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,,,,,,,,,,,,

In [8]:
y = df.iloc[:,0]
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: Disease, Length: 4920, dtype: object

In [9]:
X = X.astype(str).agg(" ".join, axis=1)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer()

X_train_transformed = vector.fit_transform(X_train)
X_test_transformed = vector.transform(X_test)

In [12]:

from sklearn.naive_bayes import MultinomialNB

In [13]:
model = MultinomialNB()

In [14]:
model.fit(X_train_transformed, y_train)

MultinomialNB()

In [15]:
y_pred = model.predict(X_test_transformed)
y_pred

array(['Acne', 'Acne', 'Hyperthyroidism', ..., 'Hypothyroidism',
       'Psoriasis', 'Pneumonia'], shape=(1230,), dtype='<U39')

In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [17]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        23
                                   AIDS       1.00      1.00      1.00        36
                                   Acne       1.00      1.00      1.00        33
                    Alcoholic hepatitis       1.00      1.00      1.00        29
                                Allergy       1.00      1.00      1.00        29
                              Arthritis       1.00      1.00      1.00        30
                       Bronchial Asthma       1.00      1.00      1.00        38
                   Cervical spondylosis       1.00      1.00      1.00        29
                            Chicken pox       1.00      1.00      1.00        30
                    Chronic cholestasis       1.00      1.00      1.00        21
                            Common Cold       1.00      1.00      1.00        29
                                 Dengue       1.00      1.00      1.00        29
                              Diabetes        1.00      1.00      1.00        29
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        37
                          Drug Reaction       1.00      1.00      1.00        30
                       Fungal infection       1.00      1.00      1.00        23
                                   GERD       1.00      1.00      1.00        37
                        Gastroenteritis       1.00      1.00      1.00        33
                           Heart attack       1.00      1.00      1.00        31
                            Hepatitis B       1.00      1.00      1.00        38
                            Hepatitis C       1.00      1.00      1.00        32
                            Hepatitis D       1.00      1.00      1.00        27
                            Hepatitis E       1.00      1.00      1.00        39
                          Hypertension        1.00      1.00      1.00        26
                        Hyperthyroidism       1.00      1.00      1.00        26
                           Hypoglycemia       1.00      1.00      1.00        32
                         Hypothyroidism       1.00      1.00      1.00        30
                               Impetigo       1.00      1.00      1.00        30
                               Jaundice       1.00      1.00      1.00        28
                                Malaria       1.00      1.00      1.00        25
                               Migraine       1.00      1.00      1.00        32
                        Osteoarthristis       1.00      1.00      1.00        23
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        29
                    Peptic ulcer diseae       1.00      1.00      1.00        21
                              Pneumonia       1.00      1.00      1.00        34
                              Psoriasis       1.00      1.00      1.00        29
                           Tuberculosis       1.00      1.00      1.00        30
                                Typhoid       1.00      1.00      1.00        25
                Urinary tract infection       1.00      1.00      1.00        33
                         Varicose veins       1.00      1.00      1.00        28
                            hepatitis A       1.00      1.00      1.00        37

                               accuracy                           1.00      1230
                              macro avg       1.00      1.00      1.00      1230
                           weighted avg       1.00      1.00      1.00      1230

In [19]:
sample = X_test.iloc[0]

sample_vector = vector.transform([sample])

prediction = model.predict(sample_vector)

print("Predicted Disease :", prediction[0])

Predicted Disease : Acne

In [20]:
print("Actual Disease :", y_test.iloc[0])

Actual Disease : Acne