In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\dell\Desktop\machine learning\pizza_prediction\pizza.csv.xls")
df

,company,price_rupiah,diameter,topping,variant,size,extra_sauce,extra_cheese,extra_mushrooms
0,A,"Rp235,000",22 inch,chicken,double_signature,jumbo,yes,yes,no
1,A,"Rp198,000",20 inch,papperoni,double_signature,jumbo,yes,yes,no
2,A,"Rp120,000",16 inch,mushrooms,double_signature,reguler,yes,yes,yes
3,A,"Rp155,000",14 inch,smoked_beef,double_signature,reguler,yes,no,yes
4,A,"Rp248,000",18 inch,mozzarella,double_signature,jumbo,yes,no,yes
...,...,...,...,...,...,...,...,...,...
124,E,"Rp39,000",8.5 inch,tuna,spicy tuna,small,yes,yes,yes
125,E,"Rp72,000",12 inch,tuna,spicy tuna,medium,yes,yes,yes
126,E,"Rp99,000",14 inch,tuna,spicy tuna,large,yes,yes,yes
127,E,"Rp44,000",8.5 inch,meat,BBQ_meat_fiesta,small,yes,no,yes
128,E,"Rp78,000",12 inch,meat,BBQ_meat_fiesta,medium,no,no,yes

In [3]:
df["company"].unique()

array(['A', 'B', 'C', 'D', 'E'], dtype=object)

In [4]:
df["topping"].unique()

array(['chicken', 'papperoni', 'mushrooms', 'smoked_beef', 'mozzarella',
       'black_papper', 'tuna', 'meat', 'sausage', 'onion', 'vegetables',
       'beef'], dtype=object)

In [5]:
df["variant"].unique()

array(['double_signature', 'american_favorite', 'super_supreme',
       'meat_lovers', 'double_mix', 'classic', 'crunchy', 'new_york',
       'double_decker', 'spicy_tuna', 'BBQ_meat_fiesta', 'BBQ_sausage',
       'extravaganza', 'meat_eater', 'gournet_greek', 'italian_veggie',
       'thai_veggie', 'american_classic', 'neptune_tuna', 'spicy tuna'],
      dtype=object)

In [6]:
df["size"].unique()

array(['jumbo', 'reguler', 'small', 'medium', 'large', 'XL'], dtype=object)

In [7]:
#Missing values check
df.isnull().sum()

company            0
price_rupiah       0
diameter           0
topping            0
variant            0
size               0
extra_sauce        0
extra_cheese       0
extra_mushrooms    0
dtype: int64

In [8]:
#duplicate value check
df.duplicated().sum()

np.int64(2)

In [9]:
df.drop_duplicates()

,company,price_rupiah,diameter,topping,variant,size,extra_sauce,extra_cheese,extra_mushrooms
0,A,"Rp235,000",22 inch,chicken,double_signature,jumbo,yes,yes,no
1,A,"Rp198,000",20 inch,papperoni,double_signature,jumbo,yes,yes,no
2,A,"Rp120,000",16 inch,mushrooms,double_signature,reguler,yes,yes,yes
3,A,"Rp155,000",14 inch,smoked_beef,double_signature,reguler,yes,no,yes
4,A,"Rp248,000",18 inch,mozzarella,double_signature,jumbo,yes,no,yes
...,...,...,...,...,...,...,...,...,...
124,E,"Rp39,000",8.5 inch,tuna,spicy tuna,small,yes,yes,yes
125,E,"Rp72,000",12 inch,tuna,spicy tuna,medium,yes,yes,yes
126,E,"Rp99,000",14 inch,tuna,spicy tuna,large,yes,yes,yes
127,E,"Rp44,000",8.5 inch,meat,BBQ_meat_fiesta,small,yes,no,yes
128,E,"Rp78,000",12 inch,meat,BBQ_meat_fiesta,medium,no,no,yes

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   company          129 non-null    object
 1   price_rupiah     129 non-null    object
 2   diameter         129 non-null    object
 3   topping          129 non-null    object
 4   variant          129 non-null    object
 5   size             129 non-null    object
 6   extra_sauce      129 non-null    object
 7   extra_cheese     129 non-null    object
 8   extra_mushrooms  129 non-null    object
dtypes: object(9)
memory usage: 9.2+ KB

In [11]:
df["price_rupiah"].head()

0    Rp235,000
1    Rp198,000
2    Rp120,000
3    Rp155,000
4    Rp248,000
Name: price_rupiah, dtype: object

In [12]:
df["price_rupiah"]

0      Rp235,000
1      Rp198,000
2      Rp120,000
3      Rp155,000
4      Rp248,000
         ...
124     Rp39,000
125     Rp72,000
126     Rp99,000
127     Rp44,000
128     Rp78,000
Name: price_rupiah, Length: 129, dtype: object

In [13]:
df.columns

Index(['company', 'price_rupiah', 'diameter', 'topping', 'variant', 'size',
       'extra_sauce', 'extra_cheese', 'extra_mushrooms'],
      dtype='object')

In [14]:
df["price_rupiah"]=df["price_rupiah"].str.replace("Rp","")

In [15]:
df["price_rupiah"]=df["price_rupiah"].str.replace(",","")

In [16]:
df["price_rupiah"]=df["price_rupiah"].astype(int)

In [17]:
#Diameter
df["diameter"]=df["diameter"].str.replace(" inch","")
df["diameter"]=df["diameter"].astype(float)

In [18]:
#Label encoding

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df["company"]=encoder.fit_transform(df["company"])
df["topping"]=encoder.fit_transform(df["topping"])
df["variant"]=encoder.fit_transform(df["variant"])
df["size"]=encoder.fit_transform(df["size"])
df["extra_sauce"]=encoder.fit_transform(df["extra_sauce"])
df["extra_cheese"]=encoder.fit_transform(df["extra_cheese"])
df["extra_mushrooms"]=encoder.fit_transform(df["extra_mushrooms"])

In [19]:
df

,company,price_rupiah,diameter,topping,variant,size,extra_sauce,extra_cheese,extra_mushrooms
0,0,235000,22.0,2,8,1,1,1,0
1,0,198000,20.0,7,8,1,1,1,0
2,0,120000,16.0,5,8,4,1,1,1
3,0,155000,14.0,9,8,4,1,0,1
4,0,248000,18.0,4,8,1,1,0,1
...,...,...,...,...,...,...,...,...,...
124,4,39000,8.5,10,16,5,1,1,1
125,4,72000,12.0,10,16,3,1,1,1
126,4,99000,14.0,10,16,2,1,1,1
127,4,44000,8.5,3,0,5,1,0,1
128,4,78000,12.0,3,0,3,0,0,1

In [20]:
X=df.drop("price_rupiah", axis=1)

Y=df["price_rupiah"]

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import *
from sklearn.metrics import r2_score

In [22]:
X_train, X_test, Y_train, Y_test =train_test_split(X,Y, test_size=0.3,random_state=42) 
Y_test

55      39000
40      76000
19      90000
31      31000
114     72000
56      72000
69      84000
105     96000
81      70000
26      46000
95      31000
27      72000
64      44000
4      248000
97      93000
100     23500
36     123000
80     110000
93      83000
84     230000
18      90000
10     140000
119     46000
11     110000
124     39000
45      72000
70      39000
78      92000
47      83000
0      235000
12      70000
42     126500
127     44000
24     149000
67      28000
112     33000
89      23500
15     140000
77      54000
Name: price_rupiah, dtype: int64

In [23]:
#Multiple Linear Regression
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X_train, Y_train)

LinearRegression()

In [24]:
X_test_predict = regression.predict(X_test)
X_test_predict

array([ 50142.13831763,  65584.41434018,  89998.85352182,  50012.58920886,
        88862.0792672 ,  80068.08675083, 100196.97983367,  62427.92423718,
        15310.68112101,  68981.16602552,  42147.02538819, 101799.67383628,
        44336.61886783, 145384.75384872,  88647.06997584,  38627.02066767,
        85599.24269973, 110550.63076006, 107034.70315494, 201805.48011255,
        91443.32504275, 143132.19058061,  70488.28666575, 106794.12866668,
        46888.89717676,  94524.95094074,  48532.0216324 ,  97761.9197714 ,
       107680.73329614, 204249.21256378,  30154.69633671,  78432.07431115,
        38503.33386852, 151455.40710284,  47563.82423623,  36228.92366977,
        40754.91915814, 151950.33987143,  78664.47944689])

In [25]:
from sklearn.metrics import r2_score
score=r2_score(Y_test, X_test_predict)
print(score)

0.7595426164792705

In [26]:
ridge_regression=Ridge(alpha=0.8)
ridge_regression.fit(X_train,Y_train)

Ridge(alpha=0.8)

In [27]:
X_test_predict_ridge=ridge_regression.predict(X_test)
r2_score(Y_test,X_test_predict_ridge)

0.7596152834216381

In [28]:
lasso_regression=Lasso(alpha=0.8)
lasso_regression.fit(X_train,Y_train)

Lasso(alpha=0.8)

In [29]:
X_test_predict_lasso=lasso_regression.predict(X_test)
r2_score(Y_test,X_test_predict_lasso)

0.7595442852874976